input_data_path: 'data/'
data_file_name: 'heart_cleveland_upload.csv'
output_model_path: 'models/model.pkl'
metric_path: 'models/metrics.json'
splitting_params:
    - 'val_size': 0.2
    - 'random_state': 42
train_params:
    - 'n_estimators': 100
    - 'lr': 0.003
    - 'max_depth': 5
    - 'random_state': 42
feature_cols:
    - 'age'
    - 'sex'
    - 'cp'
    - 'trestbps'
    - 'chol'
    - 'fbs'
    - 'restecg'
    - 'thalach'
    - 'exang'
    - 'oldpeak'
    - 'slope'
    - 'ca'
    - 'thal'
target_col: 
    - 'condition'